# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('hora', models.DateTimeField(verbose_name='hora')),
                ('duracion', models.DurationField(verbose_name='duración')),
                ('descripcion', models.TextField(null=True, verbose_name='descripción de la charla')),
            ],
            options={
                'verbose_name_plural': 'charlas',
                'verbose_name': 'charla',
            },
        ),
        migrations.CreateModel(
            name='FotoCharla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotoscharla')),
                ('charla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlas.Charla')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre del lugar')),
            ],
            options={
                'verbose_name_plural': 'lugares',
                'verbose_name': 'lugar',
            },
        ),
        migrations.CreateModel(
            name='Orador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('bio', models.TextField(verbose_name='curriculum vitae')),
                ('foto', models.ImageField(upload_to='fotosorador', verbose_name='foto')),
            ],
            options={
                'verbose_name_plural': 'oradores',
                'verbose_name': 'orador',
            },
        ),
        migrations.CreateModel(
            name='UsuarioCharla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True, verbose_name='rating')),
                ('charla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlas.Charla')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='charla',
            name='asistentes',
            field=models.ManyToManyField(related_name='charlas', through='charlas.UsuarioCharla', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charla',
            name='fotos',
            field=models.ManyToManyField(related_name='fotos_charlas', through='charlas.FotoCharla', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charla',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlas.Lugar', verbose_name='lugar'),
        ),
        migrations.AddField(
            model_name='charla',
            name='orador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charlas.Orador', verbose_name='orador'),
        ),
        migrations.AlterUniqueTogether(
            name='usuariocharla',
            unique_together=set([('usuario', 'charla')]),
        ),
    ]
